version: '3'
services:
  chatgpt:
    build: .
    env_file:
      - .env
    ports:
      - "3000"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    volumes:
      - ./apiclient_cert.pem:/app/apiclient_cert.pem
      - ./apiclient_key.pem:/app/apiclient_key.pem
  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - chatgpt
    links:
      - chatgpt
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf