version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    volumes:
      - ./apiclient_cert.pem:/app/apiclient_cert.pem
      - ./apiclient_key.pem:/app/apiclient_key.pem
    depends_on:
      - redis
    links:
      - redis

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - web
    links:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  redis:
    image: redis:latest
    restart: on-failure
