version: '3'
services:
  chatgpt:
    image: chatgpt
    ports:
      - "3000"
    deploy:
      replicas: 4
  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - chatgpt
    links:
      - chatgpt
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf